[package]
name = "SmartThermostat"
version = "0.1.0"
edition = "2024"
authors = ["Tahsinur Rahman", "Hsiao-Yin Peng", "Proma Roy", "Md Ariful Islam Fahim"]

[dependencies]
anyhow = "1.0"
colored = "2.1"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
chrono-tz = "0.10.4"
rusqlite = { version = "0.32", features = ["bundled"] }
argon2 = { version = "0.5", features = ["std"] }
regex = "1.10"
rpassword = "7.0"
zeroize = "1.5"
rand = "0.8"
